name: Release

concurrency:
  group: release
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.APPCHOOSE_GITHUB_TOKEN_RELEASER }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare
        run: yarn prepare

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.APPCHOOSE_GITHUB_TOKEN_RELEASER }}
          NPM_TOKEN: ${{ secrets.APPCHOOSE_GITHUB_TOKEN_RELEASER }}
